### ISSUE TITLE
Package not working on Google BigQuery

### ISSUE THREAD

**Issue by CraigWilson-ZOE** [fivetran/dbt_mixpanel#13]
I recently upgraded to the 0.2.0 release of the package and it will no longer run for me.

However, if I run with a previous version of the package, the only change I make to the dbt project, then this runs without error in BigQuery and produces the datasets.

The error I am receiving is:
```
Completed with 1 error and 0 warnings:

Runtime Error in model stg_mixpanel__event_tmp (models/staging/tmp/stg_mixpanel__event_tmp.sql)
  404 GET https://bigquery.googleapis.com/bigquery/v2/projects/backend-producti-b8633498/queries/d53025ae-64dc-4846-802b-2080411adce6?maxResults=0&location=EU&prettyPrint=false: Not found: Job backend-producti-b8633498:EU.d53025ae-64dc-4846-802b-2080411adce6
  
  (job ID: d53025ae-64dc-4846-802b-2080411adce6)

Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

I am running all my datasets within an EU region on GCP. My `profiles.yml` file is configured as so (some fields redacted for security purposes):
```
default:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      project: xxxxxxxx
      threads: 1
      location: EU
      keyfile: /path/to/file/key_file.json
      timeout_seconds: 300
      priority: interactive
      schema: dbt_xxxx
      retries: 1
```

**Comment by fivetran-joemarkiewicz** [comment]
HI @CraigWilson-ZOE, thanks for opening this issue.

I believe the reason your runs are failing after updating to `v0.2.0` is due to the incorporation of custom schemas. By default this package will write your Mixpanel staging data to a schema titled (<target_schema> + _stg_mixpanel) and Mixpanel final models within a schema titled (<target_schema> + mixpanel). We have seen this cause errors for some customers where the new custom schema is not within the appropriate region (see slack thread [here](https://getdbt.slack.com/archives/C01D1R2JLLA/p1617698421108000)).

As such, I believe the fix to this would be to override the custom schemas within you `dbt_project.yml` by adding the following config to your models section:

```yml
# dbt_project.yml

...
models:
    mixpanel:
      +schema: # leave blank for just the target_schema
      staging:
        +schema: # leave blank for just the target_schema
```

This way your dbt runs will not try and create a new custom schema, but will instead use the target schema you already defined. Let me know if this fixes the error in your `v0.2.0` runs of the Mixpanel package.
