### ISSUE TITLE
[Feature] Improve run time of package with additional ftiler

### ISSUE THREAD

**Issue by CraigWilson-ZOE** [fivetran/dbt_mixpanel#38]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

When running within BigQuery I noticed that the model `stg_mixpanel__event_tmp` did not apply the same filter that the `mixpanel__event` model does i.e.:

```sql
where time >= {{ "'" ~ var('date_range_start',  '2010-01-01') ~ "'" }}
```

Applying this filter in the view can significantly reduce the resource requirements for running the model. When running in BigQuery for our own data, a run of the original code would process 4.45TB of data. Applying this filter, with the configuration below in our dbt_project.yml file, changed the processing to 276GB, which is a drastic improvement.

This is especially relevant when running in development, where you can use jinja to limit the number of records when running in development, which can greatly improve the time to test etc. e.g.

```yaml
vars:
   mixpanel:
      date_range_start: "{{ '2019-11-01' if target.name == 'production' else (modules.datetime.date.today() - modules.datetime.timedelta(7)) }}"
```

I believe applying the same variable based filtering in the temporary table, when this is used as the source of the `mixpanel__event` model is required to ensure the same amount of data is processed throughout the model.

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.
